"""blacklist token length 255 to 4096

Revision ID: 334c0dfe8803
Revises: 15fe6716ab15
Create Date: 2024-04-23 20:44:54.820742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334c0dfe8803'
down_revision: Union[str, None] = '15fe6716ab15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklist', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklist', 'token',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
