"""fix User table(role, login_limit), add Dataset table

Revision ID: a90a24e5118d
Revises: 1d048cd72307
Create Date: 2024-04-23 19:10:05.645899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a90a24e5118d'
down_revision: Union[str, None] = '1d048cd72307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'MODERATOR', 'USER', name='userrole').create(op.get_bind())
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('corrected', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('login_limit', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'MODERATOR', 'USER', name='userrole', create_type=False), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'login_limit')
    op.drop_table('dataset')
    sa.Enum('ADMIN', 'MODERATOR', 'USER', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
